# Generated by Django 2.2.10 on 2020-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200416_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Sin Nombre', max_length=100),
        ),
    ]
