# Generated by Django 2.2.10 on 2020-03-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_code', models.CharField(max_length=100, unique=True)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('car_brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('public_price', models.FloatField()),
                ('card_price', models.FloatField(null=True)),
                ('master_price', models.FloatField(null=True)),
                ('wholesale_price', models.FloatField(null=True)),
                ('dozen_price', models.FloatField(null=True)),
            ],
        ),
    ]
