# Generated by Django 2.2.10 on 2020-03-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('modelo_coche', models.CharField(max_length=100)),
                ('precio_minorista', models.FloatField()),
                ('precio_mayorista1', models.FloatField(null=True)),
                ('precio_mayorista2', models.FloatField(null=True)),
                ('precio_mayorista3', models.FloatField(null=True)),
            ],
        ),
    ]
