# Generated by Django 2.2.10 on 2020-03-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio_mayorista1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_mayorista2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_mayorista3',
            field=models.FloatField(null=True),
        ),
    ]
