# Generated by Django 2.2.10 on 2020-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='car_brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='car_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='car_year',
            field=models.IntegerField(null=True),
        ),
    ]
