# Generated by Django 2.2.10 on 2020-03-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200319_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fecha_mod',
        ),
    ]
