# Generated by Django 2.2.10 on 2020-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200716_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.TextField(default='', max_length=22),
        ),
    ]
